### PR TITLE
Update to latest gradle versions and dependencies.

### PR DESCRIPTION
**Pull request by IgorGanapolsky**

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Switch to Android sdk 23 in `.travis.yml`

**Comment by IgorGanapolsky** [comment]
@artem-zinnatullin done

**Comment by artem-zinnatullin** [comment]
@IgorGanapolsky great! But I am not a maintainer of this repo, so I can not merge this, you now need to wait for @JakeWharton or @AlecStrong :)

Also, I guess Jake will blame you for breaking formatting in `build.gradle` (2 spaces indent instead of 4) and you can squash your commits into one :)

**Comment by JakeWharton** [comment]
Don't reformat the `build.gradle`. Squash your commits.

**Comment by IgorGanapolsky** [comment]
Hello @JakeWharton, I squashed my commits.  But I have no clue to how change spacing and indentation as per your requirements.  The latest version of Android Studio forces 4 spaces on each line, and there is nothing in the settings I can do to change that.  I already looked at several StackOverflow posts where people reported the same spacing issue, but there is no solution.

**Comment by artem-zinnatullin** [comment]
You didn't squash the commits, now there are 4 of them :)

To change formatting in the AS open Settings -> Editor -> Code Style -> Groovy.

You can ping me in Twitter [@artem_zin](https://twitter.com/artem_zin/) if you need help with squashing commits :)

**Comment by JakeWharton** [comment]
Squashed and merged manually. Thanks.

**Pull request closed without merging**
