### PR TITLE
Add APIs for executing raw SQL in both trigger and no-trigger forms.

### LINKED ISSUE #57: Add execSQL to BriteDatabase
Motivation can be found at **Using a Prepared Statement** section of http://stackoverflow.com/q/1711631/892500

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #57.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Open to other names here, but `execSQL` is downright horrid.

**Comment by IgorGanapolsky** [comment]
Why is execSQL bad?

**Comment by JakeWharton** [comment]
It's an abbreviation of a word followed by an all-uppercase acronym. Both are things you should never do in an API. It should be named `executeSql`, which is what the internal method is named that it delegates to.

**Comment by AlecStrong** [comment]
`execute` and `executeSql` both sound fine.

LGTM

**Pull request merged**
