### PR TITLE
Add Travis secrets for snapshot deployment.

### LINKED ISSUE #5: Snapshots don't work. Fix ur buildz

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #5.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Bonus: we get to see if the hackjob of a `.travis.yml` I made works...

**Comment by mattprecious** [comment]
LGTM, assuming Travis is happy.

**Comment by JakeWharton** [comment]
One build timed out installing the test APK. Is there a "kill me" emoji?

**Comment by JakeWharton** [comment]
:hocho: :scream:

**Pull request merged**
