### PR TITLE
Add missing fail() to QueryTests.

### PR DESCRIPTION
**Pull request by serj-lotutovici**
Some tests that expected the Observable to throw where missing a `fail()` statement.

### CODE REVIEW

**Comment by serj-lotutovici** [comment]
`@Test public void mapToListThrowsOnMapperNull()` fails, since the call to `employees.first();` doesn't actually throw. Searched for the expected message, and didn't find any. Does this test still reflect the expected behavior?

**Comment by JakeWharton** [comment]
omg don't tell @swankjesse i forgot these

**Comment by JakeWharton** [comment]
> Does this test still reflect the expected behavior

no. see #121 for how to update the test.

**Comment by serj-lotutovici** [comment]
> omg don't tell @swankjesse i forgot these

I wont 😉 

> no. see #121 for how to update the test.

done

**Comment by JakeWharton** [comment]
Perfect. Thanks for finding and fixing!

**Pull request merged**
