### PR TITLE
Port to RxJava 2.

### LINKED ISSUE #136: Request port RxJava 2.0
Hi ,
Thanks for this library 
Any chance support Rxjava 2.0 

Thanks,
Rajesh Rajendiran

### PR DESCRIPTION
**Pull request by JakeWharton**
* Maven groupId is now `com.squareup.sqlbrite2`.
* Package name is now `com.squareup.sqlbrite2`.
* `Query.mapTo*` methods now return `ObserverOperator` instead of `Function` for use with `lift` instead of `to`.
* Backpressure is no longer supported and must be applied with operators.

Closes #136

### CODE REVIEW

**Comment by JakeWharton** [comment]
Lint just spins on the sample. Not sure why...

**Comment by iNoles** [comment]
You could have put checkReleaseBuilds false or abortOnError false under lintOptions block.

**Comment by JakeWharton** [comment]
`checkReleaseBuilds` has no effect, this is the `lint` task that's running. `abortOnError` also has no effect as the `lint` task never completes.

**Comment by JakeWharton** [comment]
Besides, adding either of those is not correct here.

**Comment by albodelu** [comment]
As a quick fix, you can try to increase travis_wait (10 minutes by default) to 20 minutes.

This bash function is discussed [here](https://github.com/travis-ci/travis-ci/issues/1962) and documented [here](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received).

You need to add the default script section to .travis.yml [like this](https://github.com/albodelu/sqlbrite/compare/056bf7b5939f...7e881d6432b7):

```
script:
  - travis_wait 20 ./gradlew build connectedCheck
```

`travis_wait` is not the better solution because it shows a green build result when a test fails, due to the `travis_wait` command finishes successfully.

It's only to see what does under the hood.

A better solution would be to try to decrease the requited time or to print something every 8 minutes [like this](https://github.com/ardock/android-topeka/blob/2fcda8ae68ee4186a84f5a08d2d337e4887c40be/scripts/acib#L317).

```
# Print delayed 8 minutes
# Print and return the text of this script delayed
function print-delayed {
    sleep 480
    print-mytext "`echo "\n"`"
}
```

I use it [like this](https://github.com/ardock/android-topeka/blob/acib/.travis.yml#L55):

```
script:
  - ./execute print-delayed & # Print script text delayed 8 minutes to avoid travis timeout
  - ./gradlew build connectedCheck
```

A Gradle task would be better in your case, this is only a dirty workaround.

**Comment by JakeWharton** [comment]
I let it run for 30m locally. It's not a problem with Travis as it should complete in a few seconds. Reverting the Android Gradle plugin update fixed it until we can jump to 3.0.

**Comment by ArazAbishov** [comment]
@JakeWharton Is there any particular reason not to use Flowable as main building block for SqlBrite? Thanks.

**Comment by JakeWharton** [comment]
Because the system doesn't support backpressure.

**Comment by ArazAbishov** [comment]
Thanks, good to know.

**Pull request merged**
